name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir released && cp target/*.jar released
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: released
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: released/*.jar