name: Build Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-manual-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir released && cp target/*.jar released
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: released